root_dir = ""
certcache_dir = "./certcache"
cert_email = "tk@gmail.com"

[domains]
"localhost:3333" = { root = "", site1 = "" }
# "example.com" = { root = "/var/www/example", blog = "/var/www/blog" }
